window.MECHANISM_STAGES = [
 {title:"Resting catalytic triad",short:"Resting triad",phase:"Acylation",pdb:"4cha",evidence:"Experimental structure",class:"experimental",summary:"The catalytic residues are preorganized, but Ser195 is not yet activated.",chemistry:"Asp102–COO⁻ ··· His57 Nδ1; His57 Nε2: ··· H–Oγ–Ser195.",bonds:"resting",energy:.12,proton:"None",forming:"None",breaking:"None",role:"Preorganization"},
 {title:"Substrate recognition and binding",short:"Binding",phase:"Acylation",pdb:"8gch",evidence:"Experimental peptide-associated structure",class:"experimental",summary:"The peptide carbonyl is oriented toward Ser195 and the oxyanion hole.",chemistry:"R_C–C(=O)–NH–R_N binds without a covalent enzyme–substrate bond.",bonds:"bound",energy:.18,proton:"None",forming:"Attack geometry only",breaking:"None",role:"Substrate orientation"},
 {title:"Ser195 activation",short:"Activate Ser",phase:"Acylation",pdb:"4cha",evidence:"Mechanistic inference",class:"inferred",summary:"His57 acts as a general base and converts Ser195 into a stronger nucleophile.",chemistry:"His57 Nε2 accepts H* from Ser195 Oγ; the O–H bond electrons remain on oxygen.",bonds:"activation",energy:.42,proton:"Ser195 Oγ → His57 Nε2",forming:"His57 Nε2–H*",breaking:"Ser195 Oγ–H*",role:"General base"},
 {title:"Nucleophilic attack",short:"Attack",phase:"Acylation",pdb:"1gg6",evidence:"Analogue-guided inference",class:"analogue",summary:"Ser195 Oγ attacks the substrate carbonyl carbon.",chemistry:"The carbonyl π electrons move to oxygen while the Ser195 Oγ–C bond forms.",bonds:"attack",energy:.80,proton:"None",forming:"Ser195 Oγ–carbonyl C",breaking:"Carbonyl π bond",role:"Covalent catalysis"},
 {title:"First tetrahedral intermediate",short:"Tetrahedral I",phase:"Acylation",pdb:"1gg6",evidence:"Experimental transition-state analogue",class:"analogue",summary:"Nucleophilic addition converts the planar peptide carbonyl into a tetrahedral intermediate.",chemistry:"The central carbon has four single bonds; Gly193 and Ser195 backbone N–H groups stabilize O⁻.",bonds:"tetrahedral",energy:.54,proton:"H* remains on His57",forming:"Ser195 Oγ–carbonyl C complete",breaking:"None",role:"Oxyanion-hole stabilization"},
 {title:"Collapse and first product departure",short:"First collapse",phase:"Acylation",pdb:"8gch",evidence:"Mechanistic inference",class:"inferred",summary:"His57 acts as a general acid as the peptide bond breaks.",chemistry:"O⁻ reforms C=O; C–N electrons move to N; His57 transfers H* to the leaving nitrogen.",bonds:"collapse",energy:.73,proton:"His57 Nε2 → peptide N",forming:"Carbonyl π bond; peptide N–H",breaking:"Scissile peptide C–N",role:"General acid"},
 {title:"Acyl–enzyme intermediate",short:"Acyl enzyme",phase:"Acylation",pdb:"1gct",evidence:"Experimental acyl-enzyme candidate",class:"experimental",summary:"A transient ester covalently links Ser195 Oγ to the acyl fragment.",chemistry:"Protein–Ser195–O–C(=O)–R_C; H₂N–R_N is the departed amine-side product.",bonds:"acyl",energy:.28,proton:"None",forming:"Acyl–enzyme ester complete",breaking:"Peptide C–N complete",role:"Covalent intermediate"},
 {title:"Water binding and activation",short:"Activate water",phase:"Deacylation",pdb:"1gct",evidence:"Mechanistic inference",class:"inferred",summary:"His57 acts again as a general base, activating bound water.",chemistry:"His57 Nε2 accepts H* from H–O–H; the water O–H bond electrons remain on oxygen.",bonds:"water",energy:.43,proton:"Water O → His57 Nε2",forming:"His57 Nε2–H*",breaking:"Water O–H*",role:"General base"},
 {title:"Water attack",short:"Water attack",phase:"Deacylation",pdb:"1gg6",evidence:"Analogue-guided inference",class:"analogue",summary:"The water-derived oxygen attacks the acyl carbonyl.",chemistry:"Water O lone pair forms C–O while the carbonyl π electrons move to oxygen.",bonds:"waterattack",energy:.78,proton:"H* remains on His57",forming:"Water O–acyl carbonyl C",breaking:"Carbonyl π bond",role:"Nucleophilic addition"},
 {title:"Second tetrahedral intermediate",short:"Tetrahedral II",phase:"Deacylation",pdb:"1gg6",evidence:"Analogue-guided inference",class:"analogue",summary:"The second tetrahedral intermediate contains the incoming water-derived oxygen, not peptide nitrogen.",chemistry:"The central carbon is bonded to R_C, Ser195 Oγ, O⁻, and water-derived OH.",bonds:"tetrahedral2",energy:.52,proton:"H* remains on His57",forming:"Water O–C complete",breaking:"None",role:"Oxyanion-hole stabilization"},
 {title:"Collapse and enzyme regeneration",short:"Regenerate",phase:"Deacylation",pdb:"4cha",evidence:"Mechanistic inference",class:"inferred",summary:"Collapse breaks the acyl–enzyme bond and regenerates Ser195.",chemistry:"O⁻ reforms C=O; the acyl C–Ser O bond electrons return to Ser; His57 returns H* to Ser195.",bonds:"deacyl",energy:.65,proton:"His57 Nε2 → Ser195 Oγ",forming:"C=O; Ser195 O–H",breaking:"Acyl C–Ser195 Oγ",role:"General acid + regeneration"},
 {title:"Carboxyl product release",short:"Product release",phase:"Deacylation",pdb:"4cha",evidence:"Resting structure + inference",class:"inferred",summary:"Free enzyme is restored and the carboxyl-side product is released.",chemistry:"Water contributes H to the amine-side product and OH to the carboxyl-side product.",bonds:"release",energy:.08,proton:"Cycle complete",forming:"Products complete",breaking:"Peptide bond hydrolyzed",role:"Enzyme regenerated"}
];
