window.MECHANISM_STAGES = [
  { title:"Free enzyme", short:"Free enzyme", phase:"Recognition", pdb:"4cha", evidence:"Experimental structure", class:"experimental", summary:"The catalytic residues are preorganized in the resting enzyme.", chemistry:"Neutral Ser195 and His57 form a hydrogen-bonded relay with Asp102.", bonds:"resting", energy:0.14 },
  { title:"Substrate recognition", short:"Recognition", phase:"Binding", pdb:"8gch", evidence:"Experimental peptide-associated structure", class:"experimental", summary:"The aromatic side chain is positioned in the specificity pocket.", chemistry:"Binding aligns the scissile carbonyl with Ser195 and the oxyanion hole.", bonds:"bound", energy:0.20 },
  { title:"Catalytic alignment", short:"Alignment", phase:"Binding", pdb:"4cha", evidence:"Structure-supported inference", class:"inferred", summary:"The triad and oxyanion-hole donors define a productive geometry.", chemistry:"Close contacts support proton transfer and nucleophilic attack; motion is schematic.", bonds:"bound", energy:0.27 },
  { title:"Ser195 activation", short:"Activate Ser", phase:"Acylation", pdb:"4cha", evidence:"Mechanistic inference", class:"inferred", summary:"His57 acts as a general base to activate Ser195.", chemistry:"A modeled proton moves from Ser195 Oγ to His57 Nε2.", bonds:"activation", energy:0.50 },
  { title:"Nucleophilic attack", short:"Attack", phase:"Acylation", pdb:"1gg6", evidence:"Analogue-guided inference", class:"analogue", summary:"Ser195 Oγ attacks the substrate carbonyl carbon.", chemistry:"The curved arrow and new bond are explanatory overlays; 1GG6 supplies tetrahedral geometry.", bonds:"attack", energy:0.82 },
  { title:"First tetrahedral state", short:"Tetrahedral I", phase:"Acylation", pdb:"1gg6", evidence:"Experimental transition-state analogue", class:"analogue", summary:"A tetrahedral oxyanion is stabilized by backbone NH donors.", chemistry:"1GG6 contains an N-acetyl-Phe trifluoromethyl ketone hemiketal analogue.", bonds:"tetrahedral", energy:0.63 },
  { title:"Collapse and amine departure", short:"Collapse", phase:"Acylation", pdb:"8gch", evidence:"Mechanistic inference", class:"inferred", summary:"The carbonyl reforms and the amine product leaves.", chemistry:"His57 donates a proton to the departing amine as the acyl enzyme forms.", bonds:"collapse", energy:0.76 },
  { title:"Acyl–enzyme", short:"Acyl enzyme", phase:"Covalent intermediate", pdb:"1gct", evidence:"Experimental acyl-enzyme candidate", class:"experimental", summary:"The substrate acyl group is covalently linked to Ser195.", chemistry:"1GCT was interpreted as a tetrapeptide acyl-enzyme adduct; assignment is presented conservatively.", bonds:"acyl", energy:0.35 },
  { title:"Water activation", short:"Activate water", phase:"Deacylation", pdb:"1gct", evidence:"Mechanistic inference", class:"inferred", summary:"His57 activates an incoming water molecule.", chemistry:"A modeled proton transfers from water to His57.", bonds:"water", energy:0.54 },
  { title:"Second tetrahedral state", short:"Tetrahedral II", phase:"Deacylation", pdb:"1gg6", evidence:"Analogue-guided inference", class:"analogue", summary:"Water-derived hydroxide attacks the acyl carbonyl.", chemistry:"The oxyanion hole stabilizes a second tetrahedral geometry; 1GG6 is reused only as a geometry analogue.", bonds:"tetrahedral2", energy:0.86 },
  { title:"Deacylation", short:"Deacylate", phase:"Deacylation", pdb:"4cha", evidence:"Mechanistic inference", class:"inferred", summary:"Collapse breaks the Ser195–acyl bond.", chemistry:"The carboxylate product forms while His57 returns a proton to Ser195.", bonds:"deacyl", energy:0.61 },
  { title:"Product release", short:"Release", phase:"Regeneration", pdb:"4cha", evidence:"Resting structure + inference", class:"inferred", summary:"Product dissociates and the resting active site is regenerated.", chemistry:"The enzyme ends the cycle chemically unchanged.", bonds:"release", energy:0.08 }
];
