"use strict";

// INSTRUCTOR EDITING GUIDE: stage labels, explanations, roles, and strategy mappings live here.
const STAGES = [
  {short:"Free E + S",title:"Free enzyme and substrate",phase:"Recognition",message:"Substrate specificity positions the aromatic side chain in the hydrophobic pocket and places the adjacent peptide bond near Ser195.",roles:["Ser195–OH is poised as the future nucleophile.","His57 is neutral in the resting triad.","Asp102 hydrogen-bonds to and organizes His57.","Not yet engaged."],strategies:["orientation"],look:"The aromatic phenyl ring approaching the deep specificity pocket.",kind:"free"},
  {short:"ES complex",title:"Enzyme–substrate complex",phase:"Binding",message:"Binding and orientation place the reacting groups in a favorable geometry—without forming a covalent bond yet.",roles:["Ser195–OH is aligned near the carbonyl carbon.","His57 hydrogen-bonds to Ser195–OH.","Asp102 stabilizes the orientation and proton-transfer behavior of His57.","Backbone N–H donors aim toward the carbonyl oxygen."],strategies:["orientation"],look:"The carbonyl carbon near Ser195 and oxygen aimed into the oxyanion hole.",kind:"bound"},
  {short:"Ser attack",title:"Ser195 activation and nucleophilic attack",phase:"Acylation",message:"His57 acts as a general base, generating the more nucleophilic Ser195 alkoxide; Ser195—not His57—attacks the carbonyl.",roles:["Loses H and its oxygen attacks the acyl carbon.","Accepts the Ser195 proton as a general base.","Hydrogen-bonds to His57; it does not remove the Ser proton directly.","Begins to stabilize developing negative charge on oxygen."],strategies:["acidbase","covalent","orientation"],look:"Two simultaneous electron movements: Oγ→carbonyl carbon and C=O π→oxygen.",kind:"attack1"},
  {short:"Tetrahedral I",title:"First tetrahedral intermediate",phase:"Acylation",message:"The carbonyl carbon becomes tetrahedral, and the oxyanion hole preferentially stabilizes the high-energy oxyanion.",roles:["Forms the new Ser–O–C covalent bond.","Remains protonated after activating Ser195.","Stabilizes and orients protonated His57.","Two backbone N–H donors stabilize O⁻ by hydrogen bonding."],strategies:["transition","electrostatic","covalent"],look:"The tetrahedral carbon has four single bonds; its O⁻ receives two hydrogen bonds.",kind:"tetra1"},
  {short:"Amine leaves",title:"Collapse and amine-product departure",phase:"Acylation",message:"His57 now acts as a general acid, helping the amine-containing product depart as the carbonyl reforms.",roles:["Remains covalently linked to the acyl group.","Donates H to the departing peptide nitrogen.","Continues to organize His57.","Stabilization diminishes as the C=O reforms."],strategies:["acidbase","covalent","transition"],look:"O⁻→C reforms C=O, C–N breaks, and nitrogen receives a proton from His57.",kind:"collapse1"},
  {short:"Acyl–enzyme",title:"Acyl–enzyme intermediate",phase:"Checkpoint",message:"Part of the substrate remains temporarily covalently attached to Ser195; the amine-containing product has fully departed.",roles:["Its oxygen forms a real covalent bond to the substrate acyl carbon.","Returns to a neutral state; water approaches.","Maintains the productive His57 orientation.","The carbonyl oxygen is positioned nearby, but is not an oxyanion now."],strategies:["covalent"],look:"The solid purple Ser195–O–C bond labeled as transient and covalent.",kind:"acyl"},
  {short:"Water attack",title:"Water activation and attack",phase:"Deacylation",message:"His57 activates water, creating the oxygen nucleophile that hydrolyzes the acyl–enzyme intermediate.",roles:["Still covalently attached to the acyl group.","Accepts a proton from water as a general base.","Organizes and stabilizes His57 during proton transfer.","Stabilizes developing negative charge as C=O π electrons move to oxygen."],strategies:["acidbase","covalent","hydrolysis"],look:"Water oxygen attacks the acyl carbon; His57 accepts H; C=O π electrons move to oxygen.",kind:"attack2"},
  {short:"Tetrahedral II",title:"Second tetrahedral intermediate",phase:"Deacylation",message:"A second tetrahedral intermediate forms and is stabilized by the same oxyanion hole.",roles:["Remains attached, but its bond is now poised to break.","Is protonated after activating water.","Continues to organize His57.","Again donates two hydrogen bonds to the oxyanion."],strategies:["transition","electrostatic","covalent","hydrolysis"],look:"Unlike tetrahedral I, this center bears a new –OH group, not an amine leaving group.",kind:"tetra2"},
  {short:"Regenerate E",title:"Collapse and enzyme regeneration",phase:"Deacylation",message:"Breakdown of the covalent intermediate regenerates Ser195–OH as the product carbonyl reforms.",roles:["The acyl C–O bond breaks; Ser195 oxygen receives H.","Returns a proton to Ser195 oxygen as a general acid.","Maintains His57 in the correct geometry.","Releases the oxyanion as the carbonyl reforms."],strategies:["acidbase","transition"],look:"O⁻ reforms C=O while the acyl–Ser bond breaks and Ser195 receives a proton.",kind:"collapse2"},
  {short:"Products",title:"Product release",phase:"Release",message:"Both products have been released, and the free enzyme is restored for another catalytic cycle.",roles:["Restored as Ser195–OH.","Neutral again in the resting arrangement.","Hydrogen-bonded to His57; it never permanently accepted the proton.","Returned to its resting, unoccupied state."],strategies:["orientation"],look:"The enzyme triad matches Stage 0 while the carboxyl product departs.",kind:"release"}
];

const STRATEGIES={orientation:["Proximity and orientation","Positions the scissile bond near Ser195."],acidbase:["General acid–base catalysis","His57 alternately accepts and donates protons."],covalent:["Covalent catalysis","Ser195 forms the acyl–enzyme intermediate."],electrostatic:["Electrostatic stabilization","The oxyanion hole stabilizes negative charge."],transition:["Transition-state stabilization","The active site favors tetrahedral transition-state-like structures."]};
const QUESTIONS=[
  {stage:2,title:"Who is the nucleophile?",prompt:"Which residue directly attacks the substrate carbonyl?",options:["Ser195","His57","Asp102","Gly193"],answer:0,feedback:"His57 activates Ser195, but the oxygen of Ser195 performs the nucleophilic attack."},
  {stage:3,title:"Stabilizing charge",prompt:"What stabilizes the negatively charged oxygen in the tetrahedral intermediate?",options:["Specificity pocket","Oxyanion hole","Asp102 alone","Water"],answer:1,feedback:"Backbone N–H groups in the oxyanion hole donate two stabilizing hydrogen bonds."},
  {stage:5,title:"The covalent checkpoint",prompt:"At which stage is substrate material covalently attached to the enzyme?",options:["ES complex","Acyl–enzyme intermediate","Product release","Free enzyme"],answer:1,feedback:"The acyl–enzyme contains a real, transient Ser195–O–C covalent bond."},
  {stage:6,title:"Deacylation nucleophile",prompt:"What is the nucleophile during deacylation?",options:["Asp102","Ser195","Water activated by His57","The amine product"],answer:2,feedback:"His57 removes a proton from water; that oxygen attacks the acyl carbonyl."},
  {stage:8,title:"Closing the cycle",prompt:"Why must the covalent intermediate eventually be broken?",options:["To regenerate free enzyme","To bind the aromatic ring","To protonate Asp102","To make His57 the nucleophile"],answer:0,feedback:"The free enzyme must be regenerated so it can catalyze another reaction."}
];

const state={stage:0,playing:false,timer:null,tutorial:false,question:0,selectedAnswers:Array(QUESTIONS.length).fill(null),strategy:null};
const $=id=>document.getElementById(id); const svgNS="http://www.w3.org/2000/svg";
const esc=s=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));

function defs(){return `<title id="svgTitle">${esc(STAGES[state.stage].title)}</title><desc id="svgDesc">Active-site diagram for stage ${state.stage}: ${esc(STAGES[state.stage].message)}</desc><defs><marker id="arrowhead" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#273543"/></marker><marker id="arrowheadBlue" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#174b83"/></marker></defs>`}
function pocket(){return `<path class="enzyme-pocket" d="M38 80Q65 35 144 35H804Q879 37 904 91V467H37Z"/><path class="pocket-cavity" d="M692 50q132 24 109 178q-15 72-77 95q18-66-9-111q-26-43-86-50q48-42 63-112Z"/><text class="label" x="724" y="93">Hydrophobic</text><text class="label" x="721" y="113">specificity pocket</text>`}
function triad(){return `<g><ellipse class="triad-ring" cx="278" cy="382" rx="225" ry="90"/><circle class="res-ser" cx="435" cy="340" r="43"/><text class="res-label" text-anchor="middle" x="435" y="336">Ser195</text><text class="res-label" text-anchor="middle" x="435" y="354">Oγ</text><circle class="res-his" cx="278" cy="390" r="43"/><text class="res-label" text-anchor="middle" x="278" y="386">His57</text><text class="res-label" text-anchor="middle" x="278" y="404">Nε2</text><circle class="res-asp" cx="120" cy="414" r="43"/><text class="res-label" text-anchor="middle" x="120" y="410">Asp102</text><text class="res-label" text-anchor="middle" x="120" y="428">COO⁻</text><path class="hbond" d="M164 408L234 396"/><path class="hbond" d="M318 371L393 350"/></g>`}
function oxyHole(){return `<g><rect class="oxy-region" x="448" y="65" width="190" height="112" rx="34"/><text class="label" x="471" y="92">Oxyanion hole</text><text class="small" x="472" y="119">Gly193 backbone N–H</text><text class="small" x="472" y="145">Ser195 backbone N–H</text></g>`}
function hBondsToO(x=604,y=205){return `<path class="hbond" d="M520 120L${x} ${y-9}"/><path class="hbond" d="M572 147L${x+3} ${y-5}"/>`}
function substrateBase(bound=true,carbonyl=true){const dx=bound?0:40;return `<g><path class="bond" d="M${760+dx} 184L${706+dx} 216L${650+dx} 202L602 235L548 222"/><path class="bond" d="M${760+dx} 184l24-42l26 42Z"/><text class="small" x="${760+dx-10}" y="130">Phe aromatic side chain</text>${carbonyl?`<path class="bond-thin" d="M602 235L602 194M612 235L612 194"/><text class="atom" x="597" y="184">O</text>`:""}<path class="bond-thin" d="M548 222L506 248"/><text class="atom" x="523" y="220">N</text><text class="small" x="515" y="276">scissile peptide bond</text><path fill="none" stroke="#b63b3b" stroke-width="2" d="M542 232L568 254"/></g>`}
function common(){return defs()+pocket()+oxyHole()+triad()}
function labelBox(text,x=540,y=406,w=330){return `<g><rect class="callout" x="${x}" y="${y}" width="${w}" height="38" rx="7"/><text class="label" text-anchor="middle" x="${x+w/2}" y="${y+25}">${text}</text></g>`}

function drawMechanism(kind){let s=common();
  if(kind==="free"){s+=substrateBase(false)+`<text class="label" x="680" y="362">Peptide substrate approaching →</text><text class="atom" x="419" y="292">OH</text>`}
  if(kind==="bound"){s+=substrateBase()+hBondsToO()+`<text class="atom" x="419" y="292">OH</text><path class="hbond" d="M435 300L604 244"/><text class="small" x="625" y="318">Noncovalent ES complex</text>`}
  if(kind==="attack1"){s+=substrateBase()+hBondsToO()+`<text class="atom" x="419" y="292">O</text><text class="charge" x="444" y="283">−</text><text class="charge" x="300" y="345">H⁺</text><path class="proton-arrow" d="M427 300Q358 285 301 347"/><path class="arrow" d="M454 302Q520 269 594 240"/><path class="arrow" d="M612 214Q650 187 618 170"/>`}
  if(kind==="tetra1"){s+=`<path class="bond" d="M770 184L706 216L650 202L604 235L548 222L506 248"/><path class="bond" d="M770 184l24-42l26 42Z" fill="none"/><text class="small" x="758" y="130">Phe aromatic side chain</text><path class="bond-thin" d="M604 235L604 185"/><text class="atom" x="595" y="171">O</text><text class="charge" x="620" y="163">−</text><path class="bond-thin" d="M604 235L548 222"/><text class="atom" x="523" y="220">N</text><path class="covalent-bond" d="M604 235L465 319"/>${hBondsToO(604,178)}<text class="charge" x="298" y="345">H⁺</text>${labelBox("Tetrahedral center: four single bonds",545,405,320)}`}
  if(kind==="collapse1"){s+=`<path class="bond" d="M770 184L706 216L650 202L604 235"/><path class="bond" d="M770 184l24-42l26 42Z" fill="none"/><text class="atom" x="596" y="172">O⁻</text><path class="bond-thin" d="M604 235L604 186"/><path class="bond breaking" d="M604 235L548 222"/><path class="product" d="M536 223L495 248L459 233"/><text class="atom" x="518" y="220">N</text><text class="small" x="462" y="275">amine product departing</text><path class="covalent-bond" d="M604 235L465 319"/>${hBondsToO(604,178)}<path class="arrow" d="M612 180Q650 200 616 226"/><path class="arrow" d="M584 232Q552 269 518 242"/><path class="proton-arrow" d="M299 350Q374 301 508 220"/>`}
  if(kind==="acyl"){s+=`<path class="bond" d="M770 184L706 216L650 202L604 235"/><path class="bond" d="M770 184l24-42l26 42Z" fill="none"/><path class="bond-thin" d="M600 235L600 188M611 235L611 188"/><text class="atom" x="596" y="178">O</text><path class="covalent-bond" d="M604 235L465 319"/><path class="bond-thin" d="M340 240L360 218L380 240"/><text class="atom" x="347" y="209">H₂O</text><path class="hbond" d="M370 220L300 353"/>${labelBox("Acyl–enzyme intermediate",540,388,330)}<text class="small" x="549" y="455">transient covalent enzyme–substrate bond</text><path stroke="#713f91" stroke-width="2" d="M626 446L535 364L477 329"/>`}
  if(kind==="attack2"){s+=`<path class="bond" d="M770 184L706 216L650 202L604 235"/><path class="bond" d="M770 184l24-42l26 42Z" fill="none"/><path class="bond-thin" d="M600 235L600 188M611 235L611 188"/><text class="atom" x="596" y="178">O</text><path class="covalent-bond" d="M604 235L465 319"/><text class="atom" x="480" y="230">H₂O</text><path class="proton-arrow" d="M493 232Q405 263 303 350"/><path class="arrow" d="M500 240Q548 250 594 239"/><path class="arrow" d="M612 210Q647 185 618 170"/><text class="charge" x="299" y="345">H⁺</text>`}
  if(kind==="tetra2"){s+=`<path class="bond" d="M770 184L706 216L650 202L604 235"/><path class="bond" d="M770 184l24-42l26 42Z" fill="none"/><path class="bond-thin" d="M604 235L604 185"/><text class="atom" x="595" y="171">O</text><text class="charge" x="620" y="163">−</text><path class="bond-thin" d="M604 235L668 268"/><text class="atom" x="671" y="278">OH</text><path class="covalent-bond" d="M604 235L465 319"/>${hBondsToO(604,178)}<text class="charge" x="298" y="345">H⁺</text>${labelBox("Tetrahedral II: newly added –OH",545,405,320)}`}
  if(kind==="collapse2"){s+=`<path class="bond" d="M770 184L706 216L650 202L604 235"/><path class="bond" d="M770 184l24-42l26 42Z" fill="none"/><path class="bond-thin" d="M604 235L604 185"/><text class="atom" x="595" y="171">O⁻</text><path class="bond-thin" d="M604 235L668 268"/><text class="atom" x="671" y="278">OH</text><path class="bond breaking" d="M604 235L465 319"/><path class="arrow" d="M610 178Q651 198 616 226"/><path class="arrow" d="M574 251Q522 293 471 318"/><path class="proton-arrow" d="M300 350Q358 320 431 322"/>`}
  if(kind==="release"){s+=`<text class="atom" x="419" y="292">OH</text><path class="product" d="M650 204L712 178L770 202"/><path class="product" d="M650 204L650 157"/><text class="atom" x="640" y="145" style="fill:var(--product)">O</text><text class="atom" x="622" y="211" style="fill:var(--product)">HO</text><text class="small" x="689" y="238">carboxyl product leaving →</text>`}
  $("mechanismSvg").innerHTML=s; applySvgClasses();
}
function applySvgClasses(){const svg=$("mechanismSvg");svg.classList.toggle("show-arrows",$("arrowsToggle").checked);svg.classList.toggle("show-charges",$("chargesToggle").checked);svg.classList.toggle("show-hbonds",$("hbondsToggle").checked);svg.classList.toggle("triad-highlight",$("triadToggle").checked);svg.classList.toggle("oxy-highlight",$("oxyToggle").checked);svg.classList.toggle("covalent-highlight",$("covalentToggle").checked)}
function render(){const st=STAGES[state.stage];$("stageNumber").textContent=`Stage ${state.stage} of 9`;$("stageTitle").textContent=st.title;$("phaseBadge").textContent=st.phase;$("stepMessage").textContent=st.message;$("lookFor").textContent=st.look;const names=["Ser195","His57","Asp102","Oxyanion hole"];$("roleList").innerHTML=names.map((n,i)=>`<dt>${n}</dt><dd>${esc(st.roles[i])}</dd>`).join("");$("strategyTags").innerHTML=st.strategies.map(k=>`<span>${esc((STRATEGIES[k]||[k])[0])}</span>`).join("");document.querySelectorAll(".stage-button").forEach((b,i)=>{b.classList.toggle("active",i===state.stage);b.setAttribute("aria-current",i===state.stage?"step":"false")});drawMechanism(st.kind);drawEnergy();}
function setStage(n){state.stage=Math.max(0,Math.min(9,n));render()}
function stop(){state.playing=false;clearInterval(state.timer);state.timer=null;$("playBtn").textContent="▶ Play";$("playBtn").setAttribute("aria-label","Play mechanism")}
function play(){if(state.playing){stop();return}state.playing=true;$("playBtn").textContent="❚❚ Pause";$("playBtn").setAttribute("aria-label","Pause mechanism");state.timer=setInterval(()=>{if(state.stage===9){stop();return}setStage(state.stage+1)},Number($("speedSelect").value))}
function reset(){stop();state.stage=0;state.strategy=null;state.question=0;state.tutorial=false;state.selectedAnswers.fill(null);$("arrowsToggle").checked=true;$("chargesToggle").checked=true;$("hbondsToggle").checked=true;$("triadToggle").checked=false;$("oxyToggle").checked=false;$("covalentToggle").checked=false;$("speedSelect").value="2600";$("uncatalyzedToggle").checked=false;document.querySelectorAll(".strategy-card").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".stage-button").forEach(b=>b.classList.remove("strategy-hit"));if($("tutorialDialog").open)$("tutorialDialog").close();render()}

function initTimeline(){$("timeline").innerHTML=STAGES.map((s,i)=>`<button class="stage-button" data-stage="${i}" aria-label="Stage ${i}: ${esc(s.title)}"><span class="dot">${i}</span><span>${esc(s.short)}</span></button>`).join("");$("timeline").addEventListener("click",e=>{const b=e.target.closest("button");if(b){stop();setStage(Number(b.dataset.stage))}})}
function initStrategies(){$("strategyCards").innerHTML=Object.entries(STRATEGIES).map(([k,v])=>`<button class="strategy-card" data-strategy="${k}"><strong>${v[0]}</strong><span>${v[1]}</span></button>`).join("");$("strategyCards").addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;state.strategy=state.strategy===b.dataset.strategy?null:b.dataset.strategy;document.querySelectorAll(".strategy-card").forEach(x=>x.classList.toggle("active",x.dataset.strategy===state.strategy));document.querySelectorAll(".stage-button").forEach((x,i)=>x.classList.toggle("strategy-hit",!!state.strategy&&STAGES[i].strategies.includes(state.strategy)))})}
function drawEnergy(){if($("energyPanel").hidden)return;const showU=$("uncatalyzedToggle").checked;const points=[[60,245],[190,205],[320,70],[455,205],[590,86],[720,220],[925,252]];const d=points.map((p,i)=>(i?"L":"M")+p.join(" ")).join(" ");const labels=[[60,278,"E + S"],[190,190,"ES"],[320,48,"Tetrahedral I"],[455,225,"Acyl–enzyme"],[590,64,"Tetrahedral II"],[720,239,"EP"],[925,280,"E + products"]];$("energySvg").innerHTML=`<defs><marker id="eArrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#14263b"/></marker></defs><path d="M50 292H965" stroke="#14263b" marker-end="url(#eArrow)"/><path d="M50 292V25" stroke="#14263b" marker-end="url(#eArrow)"/><text x="455" y="322" font-weight="700">Reaction coordinate →</text><text transform="translate(18 210) rotate(-90)" font-weight="700">Free energy</text><path d="${d}" fill="none" stroke="#174b83" stroke-width="5" stroke-linejoin="round"/>${showU?`<path d="M60 245Q420 -55 925 252" fill="none" stroke="#b63b3b" stroke-width="4" stroke-dasharray="11 8"/><text x="690" y="77" fill="#b63b3b" font-weight="700">simplified uncatalyzed</text>`:""}${labels.map(([x,y,t])=>`<circle cx="${x}" cy="${points[labels.indexOf(labels.find(a=>a[0]===x))]?.[1]||y}" r="7" fill="#713f91"/><text x="${x}" y="${y}" text-anchor="middle" font-size="14" font-weight="700">${t}</text>`).join("")}<text x="745" y="201" fill="#174b83" font-weight="700">catalyzed</text>`}
function openTutorial(){stop();state.tutorial=true;state.question=0;state.selectedAnswers.fill(null);showQuestion();$("tutorialDialog").showModal()}
function showQuestion(){const q=QUESTIONS[state.question];setStage(q.stage);$("tutorialTitle").textContent=q.title;$("tutorialPrompt").textContent=q.prompt;$("tutorialProgress").textContent=`Question ${state.question+1} of ${QUESTIONS.length}`;$("tutorialOptions").innerHTML=q.options.map((o,i)=>`<button type="button" class="tutorial-option" data-answer="${i}">${esc(o)}</button>`).join("");$("tutorialFeedback").textContent="";$("tutorialFeedback").className="feedback";$("tutorialNext").disabled=true;$("tutorialNext").textContent=state.question===QUESTIONS.length-1?"Finish":"Continue"}
function answerQuestion(i){if(state.selectedAnswers[state.question]!==null)return;const q=QUESTIONS[state.question],ok=i===q.answer;state.selectedAnswers[state.question]=i;document.querySelectorAll(".tutorial-option").forEach((b,j)=>{b.disabled=true;if(j===i)b.classList.add("selected",ok?"correct":"incorrect")});$("tutorialFeedback").textContent=(ok?"Correct. ":"Not quite. ")+q.feedback;$("tutorialFeedback").classList.add(ok?"correct":"incorrect");$("tutorialNext").disabled=false}
function initEvents(){$("prevBtn").onclick=()=>{stop();setStage(state.stage-1)};$("nextBtn").onclick=()=>{stop();setStage(state.stage+1)};$("playBtn").onclick=play;$("resetBtn").onclick=reset;$("speedSelect").onchange=()=>{if(state.playing){stop();play()}};["arrowsToggle","chargesToggle","hbondsToggle","triadToggle","oxyToggle","covalentToggle"].forEach(id=>$(id).onchange=applySvgClasses);$("energyTab").onclick=()=>{const open=$("energyPanel").hidden;$("energyPanel").hidden=!open;$("energyTab").setAttribute("aria-selected",String(open));drawEnergy()};$("uncatalyzedToggle").onchange=drawEnergy;$("tutorialStart").onclick=openTutorial;$("tutorialOptions").onclick=e=>{const b=e.target.closest("button");if(b)answerQuestion(Number(b.dataset.answer))};$("tutorialNext").onclick=()=>{if(state.question<QUESTIONS.length-1){state.question++;showQuestion()}else{$("tutorialDialog").close();state.tutorial=false;setStage(9)}};window.addEventListener("keydown",e=>{if($("tutorialDialog").open||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.key==="ArrowLeft"){e.preventDefault();stop();setStage(state.stage-1)}if(e.key==="ArrowRight"){e.preventDefault();stop();setStage(state.stage+1)}if(e.code==="Space"){e.preventDefault();play()}if(e.key.toLowerCase()==="r"){e.preventDefault();reset()}})}

initTimeline();initStrategies();initEvents();render();
